/*
# Get user info
*/
GET /api/user HTTP/1.1
Host: localhost:8001
Authorization: Bearer {{$global.token}}

?? status == 200

HTTP/1.1 200  - OK
access-control-allow-credentials: true
access-control-allow-headers: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With
access-control-allow-methods: POST, OPTIONS, GET, PUT, DELETE
access-control-allow-origin: *
content-type: application/json; charset=utf-8
date: Thu, 13 Mar 2025 14:45:35 GMT
content-length: 102
connection: close